import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

// * References
// * Parallel Routes: https://nextjs.org/docs/app/building-your-application/routing/parallel-routes

export default function RootLayout({ children, analytics, team }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="flex  flex-col items-center justify-between p-24">
					{children}
					<div className="lg:flex flex-none">
						<div className="lg:mr-5 lg:mb-0 mb-5">{team}</div>
						<div>{analytics}</div>
					</div>
				</main>
			</body>
		</html>
	);
}
